### ISSUE TITLE
Disney Infinity Emulator

### ISSUE THREAD

**Issue by NBAPJ** [cmdwtf/Odiin#92] opened 2020-10-28 14:28 UTC
Here is a link to his YouTube channel.  He has a few videos posted.

https://m.youtube.com/watch?v=yT7FT1VdZQo&list=LLpj0mbwhViM185rLdQIxgNA&index=2&t=9s

His name is obiima on YouTube

**Comment by nitz** [comment] 2020-10-29 13:31
Closed as duplicate of #93

**Closed by nitz** 2020-10-29 13:31 UTC
